ARG REGISTRY=
ARG TAG=:latest
FROM ${REGISTRY}simbricks/simbricks-local${TAG}

COPY packer /simbricks/images
COPY install-shm-rw.sh /simbricks/images/scripts

WORKDIR /simbricks/images
RUN mkdir input-shm-rw
COPY shm_rw input-shm-rw
COPY guestinit.sh input-shm-rw

RUN ./packer-wrap.sh base shm-rw extended-image.pkr.hcl false
#RUN qemu-img convert -f qcow2 -O raw /simbricks/images/output-shm-rw/shm-rw /simbricks/images/output-shm-rw/shm-rw.raw
